version: '3.4'

services:
  postgresql:
    # https://hub.docker.com/_/postgres
    image: postgres
    env_file:
      # o postgres nao vai levar em consideração a variável POSTGRES_PORT
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      # Pasta de volume criada automaticamente pelo Docker
      - postgres_data:/var/lib/postgresql/data

  # Django
  django:
    image: django
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    environment:
      # postgresql é a refência interna de host que o docker cria
      POSTGRES_HOST: 'postgresql'
      POSTGRES_PORT: "5432"
    depends_on:
      - postgresql
    command: "sh -c 'gunicorn project.wsgi:application --bind 0.0.0.0:8000'"

  front:
    image: front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/dist:/frontapp/dist

    command: "npm run build"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - front

volumes:
  postgres_data:
