# Generated by Django 4.2.6 on 2023-12-20 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("cpf", models.CharField(max_length=14)),
                ("rg", models.CharField(max_length=8)),
                ("birth_date", models.DateField()),
                ("phone", models.CharField(max_length=12)),
                ("cellphone", models.CharField(max_length=12)),
                ("email", models.EmailField(max_length=254)),
                ("father_name", models.TextField()),
                ("mother_name", models.TextField()),
                ("childrens_quantity", models.IntegerField()),
                (
                    "education_level",
                    models.TextField(
                        choices=[
                            ("fundamental", "Ensino fundamental"),
                            ("medio", "Ensino médio"),
                            ("superior", "Ensino superior"),
                        ]
                    ),
                ),
                ("profession", models.TextField()),
                (
                    "marital_status",
                    models.TextField(
                        choices=[
                            ("solteiro", "Solteiro"),
                            ("casado", "Casado"),
                            ("divorciado", "Divorciado"),
                            ("viuvo", "Viúvo"),
                        ]
                    ),
                ),
                ("address", models.TextField()),
                ("city", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("code", models.TextField()),
                ("start_date", models.DateField()),
                ("description", models.TextField()),
                ("client", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.client")),
            ],
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.process"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evolution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.process"),
                ),
            ],
        ),
    ]
