# Generated by Django 4.2.6 on 2023-12-20 03:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_client_process_observation_evolution"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2023, 12, 20, 3, 5, 14, 408319, tzinfo=datetime.timezone.utc),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="process",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="processes", to="core.client"
            ),
        ),
    ]
