# Generated by Django 4.2.6 on 2023-12-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_client_created_at_alter_process_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="type",
            field=models.TextField(
                choices=[
                    ("registro de marcas", "Registro de marcas"),
                    ("registro de patentes", "Registro de patentes"),
                    ("registro de direito autoral", "Registro de direito autoral"),
                    ("registro de softwares", "Registro de softwares"),
                    ("registro de desenho industrial", "Registro de desenho industrial"),
                    ("recuperação de ativos", "Recuperação de ativos"),
                    ("pericia judiciais", "Pericia judiciais"),
                    ("pericia extrajudiciais", "Pericia extrajudiciais"),
                    ("terceirização para escritórios", "Terceirização para escritórios"),
                ],
                default="registro de marcas",
            ),
            preserve_default=False,
        ),
    ]
