# Generated by Django 4.2.6 on 2023-12-26 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_client_profile_image_honorary"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="assigned_attendant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="evolution",
            name="created_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="evolution",
            name="process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="evolutions", to="core.process"
            ),
        ),
        migrations.AlterField(
            model_name="honorary",
            name="created_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="honorary",
            name="process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="honoraries", to="core.process"
            ),
        ),
        migrations.AlterField(
            model_name="observation",
            name="created_by",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="observation",
            name="process",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="observations", to="core.process"
            ),
        ),
        migrations.AlterField(
            model_name="process",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="processes", to="core.client"
            ),
        ),
    ]
