# Generated by Django 4.2.6 on 2023-12-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_client_assigned_attendant_alter_evolution_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
