# Generated by Django 4.2.6 on 2023-12-27 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_client_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="evolution",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="evolution_files/"),
        ),
    ]
