name: Testes

on: [push]

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.4.0
        poetry config virtualenvs.create false
        poetry install
    - name: Run tests
      run: |
        cp .env.dev .env
        pytest
